name: Auto Linter

on:
   push:
      paths: "*.py"

jobs:
   code:
      runs-on: ubuntu-latest
      steps:
         - name: checkout the code
           uses: actions/checkout@v7

         - name: Setup Python
         - uses: actions/setup-python@v6
           with:
               python-version: '3.13'

         - name: Install Python Linter
           run: pip install ruff
         - name: check the file linting
           run: ruff check . 
   
